[2025-05-01 17:02:37,390: INFO - main - >>>>> Stage: Data Ingestion Pipeline STARTED <<<<<
]
[2025-05-01 17:02:37,408: INFO - common - yaml file config\config.yaml loaded successfully]
[2025-05-01 17:02:37,409: INFO - common - yaml file params.yaml loaded successfully]
[2025-05-01 17:02:37,410: INFO - common - yaml file params.yaml is empty!]
[2025-05-01 17:02:37,410: ERROR - main - yaml file is empty]
Traceback (most recent call last):
  File "D:\Projects\MentalHealthMLProject\src\MentalHealth\utils\common.py", line 23, in read_yaml
    return ConfigBox(content)
           ^^^^^^^^^^^^^^^^^^
  File "box\\box.py", line 295, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\MentalHealthMLProject\main.py", line 10, in <module>
    obj.main()
  File "D:\Projects\MentalHealthMLProject\src\MentalHealth\pipeline\data_ingestion.py", line 13, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\MentalHealthMLProject\src\MentalHealth\config\configuration.py", line 9, in __init__
    self.params = read_yaml(params_file_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\MentalHealthMLProject\env\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\MentalHealthMLProject\src\MentalHealth\utils\common.py", line 26, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2025-05-01 17:03:06,639: INFO - main - >>>>> Stage: Data Ingestion Pipeline STARTED <<<<<
]
[2025-05-01 17:03:06,639: INFO - common - yaml file config\config.yaml loaded successfully]
[2025-05-01 17:03:06,641: INFO - common - yaml file params.yaml loaded successfully]
[2025-05-01 17:03:06,641: INFO - common - yaml file params.yaml is empty!]
[2025-05-01 17:03:06,641: ERROR - main - Return value of <function read_yaml at 0x00000212EA9BF4C0> of type <class 'NoneType'> does not match annotation type <class 'box.config_box.ConfigBox'>]
Traceback (most recent call last):
  File "D:\Projects\MentalHealthMLProject\main.py", line 10, in <module>
    obj.main()
  File "D:\Projects\MentalHealthMLProject\src\MentalHealth\pipeline\data_ingestion.py", line 13, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\MentalHealthMLProject\src\MentalHealth\config\configuration.py", line 9, in __init__
    self.params = read_yaml(params_file_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\MentalHealthMLProject\env\Lib\site-packages\ensure\main.py", line 875, in __call__
    raise EnsureError(msg.format(f=self.f, t=self.return_templ, valt=type(return_val)))
ensure.main.EnsureError: Return value of <function read_yaml at 0x00000212EA9BF4C0> of type <class 'NoneType'> does not match annotation type <class 'box.config_box.ConfigBox'>
[2025-05-01 17:04:20,275: INFO - main - >>>>> Stage: Data Ingestion Pipeline STARTED <<<<<
]
[2025-05-01 17:04:20,287: INFO - common - yaml file config\config.yaml loaded successfully]
[2025-05-01 17:04:20,287: INFO - common - yaml file params.yaml loaded successfully]
[2025-05-01 17:04:20,287: INFO - common - yaml file params.yaml is empty!]
[2025-05-01 17:04:20,287: ERROR - main - Return value of <function read_yaml at 0x000002346CDCF4C0> of type <class 'NoneType'> does not match annotation type <class 'box.config_box.ConfigBox'>]
Traceback (most recent call last):
  File "D:\Projects\MentalHealthMLProject\main.py", line 10, in <module>
    obj.main()
  File "D:\Projects\MentalHealthMLProject\src\MentalHealth\pipeline\data_ingestion.py", line 13, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\MentalHealthMLProject\src\MentalHealth\config\configuration.py", line 9, in __init__
    self.params = read_yaml(params_file_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\MentalHealthMLProject\env\Lib\site-packages\ensure\main.py", line 875, in __call__
    raise EnsureError(msg.format(f=self.f, t=self.return_templ, valt=type(return_val)))
ensure.main.EnsureError: Return value of <function read_yaml at 0x000002346CDCF4C0> of type <class 'NoneType'> does not match annotation type <class 'box.config_box.ConfigBox'>
[2025-05-01 17:04:50,807: INFO - main - >>>>> Stage: Data Ingestion Pipeline STARTED <<<<<
]
[2025-05-01 17:04:50,807: INFO - common - yaml file config\config.yaml loaded successfully]
[2025-05-01 17:04:50,809: INFO - main - >>>>> Stage: Data Ingestion Pipeline COMPLETED <<<<<

]
